# Docker Compose configuration for Employee Pulse Application
# Uses version 3.8 of the Docker Compose specification
version: '3.8'

# Define services that make up the application
services:
  # MongoDB database service
  mongodb:
    image: mongo:6.0
    container_name: employee-pulse-mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db    # Persist MongoDB data in a named volume
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - employee-pulse-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  # Backend NestJS API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: employee-pulse-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - CORS_ORIGIN=http://${DOMAIN_NAME}:${FRONTEND_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - employee-pulse-network

  # Frontend React application service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://${DOMAIN_NAME}:${BACKEND_PORT}/api
        - NODE_ENV=${NODE_ENV}
    container_name: employee-pulse-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - employee-pulse-network

# Define networks for service isolation
networks:
  employee-pulse-network:
    driver: bridge

# Define named volumes for persistent data
volumes:
  mongodb_data:            # Volume for storing MongoDB data 